site_name: lernOS - Keep Calm & Learn On
site_url: https://cogneon.github.io/
docs_dir: src
site_dir: ../docs/de

nav:
    - Willkommen: index.md
    - Publikationen: publications.md
    - FAQ: faq.md
    - Leitfäden:
      - lernOS für Dich: https://cogneon.github.io/lernos-for-you/de/
      - lernOS für Organisationen: https://cogneon.github.io/lernos-for-organizations/de/
    - Links:
      - lernOS Community: https://community.cogneon.de
      - Peerfinder: https://web.peerfinder.app

theme:
    name: 'material'
    palette:
        scheme: lernos
    language: de
    icon:
      repo: fontawesome/brands/github
      logo: material/home

extra_css:
  - stylesheets/extra.css

repo_name: 'cogneon/lernos'
repo_url: 'https://github.com/cogneon/lernos'

extra:
    social:
        - icon: fontawesome/brands/twitter
          link: 'https://twitter.com/lern_os'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/showcase/lern-os'
        - icon: fontawesome/brands/github
          link: 'https://github.com/cogneon'
    disqus: lernos

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - mermaid2
